# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DistributionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def distribution_community_pool_get(self, **kwargs):  # noqa: E501
        """Community pool parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_community_pool_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_community_pool_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.distribution_community_pool_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def distribution_community_pool_get_with_http_info(self, **kwargs):  # noqa: E501
        """Community pool parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_community_pool_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_community_pool_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/community_pool', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Coin]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_rewards_get(self, delegator_addr, **kwargs):  # noqa: E501
        """Get the total rewards balance from all delegations  # noqa: E501

        Get the sum of all the rewards earned by delegations by a single delegator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_get(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :return: DelegatorTotalRewards
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_rewards_get_with_http_info(delegator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_rewards_get_with_http_info(delegator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_rewards_get_with_http_info(self, delegator_addr, **kwargs):  # noqa: E501
        """Get the total rewards balance from all delegations  # noqa: E501

        Get the sum of all the rewards earned by delegations by a single delegator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_get_with_http_info(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :return: DelegatorTotalRewards
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_rewards_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_rewards_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/rewards', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DelegatorTotalRewards',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_rewards_post(self, delegator_addr, **kwargs):  # noqa: E501
        """Withdraw all the delegator's delegation rewards  # noqa: E501

        Withdraw all the delegator's delegation rewards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_post(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param WithdrawRequestBody withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_rewards_post_with_http_info(delegator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_rewards_post_with_http_info(delegator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_rewards_post_with_http_info(self, delegator_addr, **kwargs):  # noqa: E501
        """Withdraw all the delegator's delegation rewards  # noqa: E501

        Withdraw all the delegator's delegation rewards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_post_with_http_info(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param WithdrawRequestBody withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr', 'withdraw_request_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_rewards_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_rewards_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'withdraw_request_body' in params:
            body_params = params['withdraw_request_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/rewards', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_rewards_validator_addr_get(self, delegator_addr, validator_addr, **kwargs):  # noqa: E501
        """Query a delegation reward  # noqa: E501

        Query a single delegation reward by a delegator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_validator_addr_get(delegator_addr, validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_rewards_validator_addr_get_with_http_info(delegator_addr, validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_rewards_validator_addr_get_with_http_info(delegator_addr, validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_rewards_validator_addr_get_with_http_info(self, delegator_addr, validator_addr, **kwargs):  # noqa: E501
        """Query a delegation reward  # noqa: E501

        Query a single delegation reward by a delegator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_validator_addr_get_with_http_info(delegator_addr, validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr', 'validator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_rewards_validator_addr_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_rewards_validator_addr_get`")  # noqa: E501
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_delegators_delegator_addr_rewards_validator_addr_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Coin]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_rewards_validator_addr_post(self, delegator_addr, validator_addr, **kwargs):  # noqa: E501
        """Withdraw a delegation reward  # noqa: E501

        Withdraw a delegator's delegation reward from a single validator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_validator_addr_post(delegator_addr, validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :param WithdrawRequestBody1 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_rewards_validator_addr_post_with_http_info(delegator_addr, validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_rewards_validator_addr_post_with_http_info(delegator_addr, validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_rewards_validator_addr_post_with_http_info(self, delegator_addr, validator_addr, **kwargs):  # noqa: E501
        """Withdraw a delegation reward  # noqa: E501

        Withdraw a delegator's delegation reward from a single validator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_rewards_validator_addr_post_with_http_info(delegator_addr, validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :param WithdrawRequestBody1 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr', 'validator_addr', 'withdraw_request_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_rewards_validator_addr_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_rewards_validator_addr_post`")  # noqa: E501
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_delegators_delegator_addr_rewards_validator_addr_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'withdraw_request_body' in params:
            body_params = params['withdraw_request_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_withdraw_address_get(self, delegator_addr, **kwargs):  # noqa: E501
        """Get the rewards withdrawal address  # noqa: E501

        Get the delegations' rewards withdrawal address. This is the address in which the user will receive the reward funds  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_withdraw_address_get(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :return: Address
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_withdraw_address_get_with_http_info(delegator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_withdraw_address_get_with_http_info(delegator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_withdraw_address_get_with_http_info(self, delegator_addr, **kwargs):  # noqa: E501
        """Get the rewards withdrawal address  # noqa: E501

        Get the delegations' rewards withdrawal address. This is the address in which the user will receive the reward funds  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_withdraw_address_get_with_http_info(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :return: Address
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_withdraw_address_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_withdraw_address_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/withdraw_address', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Address',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_delegators_delegator_addr_withdraw_address_post(self, delegator_addr, **kwargs):  # noqa: E501
        """Replace the rewards withdrawal address  # noqa: E501

        Replace the delegations' rewards withdrawal address for a new one.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_withdraw_address_post(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param WithdrawRequestBody2 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_delegators_delegator_addr_withdraw_address_post_with_http_info(delegator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_delegators_delegator_addr_withdraw_address_post_with_http_info(delegator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_delegators_delegator_addr_withdraw_address_post_with_http_info(self, delegator_addr, **kwargs):  # noqa: E501
        """Replace the rewards withdrawal address  # noqa: E501

        Replace the delegations' rewards withdrawal address for a new one.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_delegators_delegator_addr_withdraw_address_post_with_http_info(delegator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str delegator_addr: Bech32 AccAddress of Delegator (required)
        :param WithdrawRequestBody2 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['delegator_addr', 'withdraw_request_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_delegators_delegator_addr_withdraw_address_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'delegator_addr' is set
        if ('delegator_addr' not in params or
                params['delegator_addr'] is None):
            raise ValueError("Missing the required parameter `delegator_addr` when calling `distribution_delegators_delegator_addr_withdraw_address_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'delegator_addr' in params:
            path_params['delegatorAddr'] = params['delegator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'withdraw_request_body' in params:
            body_params = params['withdraw_request_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/delegators/{delegatorAddr}/withdraw_address', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_parameters_get(self, **kwargs):  # noqa: E501
        """Fee distribution parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_parameters_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_parameters_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.distribution_parameters_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def distribution_parameters_get_with_http_info(self, **kwargs):  # noqa: E501
        """Fee distribution parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_parameters_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_parameters_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/parameters', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_validators_validator_addr_get(self, validator_addr, **kwargs):  # noqa: E501
        """Validator distribution information  # noqa: E501

        Query the distribution information of a single validator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_get(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: ValidatorDistInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_validators_validator_addr_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_validators_validator_addr_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_validators_validator_addr_get_with_http_info(self, validator_addr, **kwargs):  # noqa: E501
        """Validator distribution information  # noqa: E501

        Query the distribution information of a single validator  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_get_with_http_info(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: ValidatorDistInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['validator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_validators_validator_addr_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_validators_validator_addr_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/validators/{validatorAddr}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ValidatorDistInfo',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_validators_validator_addr_outstanding_rewards_get(self, validator_addr, **kwargs):  # noqa: E501
        """Fee distribution outstanding rewards of a single validator  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_outstanding_rewards_get(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_validators_validator_addr_outstanding_rewards_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_validators_validator_addr_outstanding_rewards_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_validators_validator_addr_outstanding_rewards_get_with_http_info(self, validator_addr, **kwargs):  # noqa: E501
        """Fee distribution outstanding rewards of a single validator  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_outstanding_rewards_get_with_http_info(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['validator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_validators_validator_addr_outstanding_rewards_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_validators_validator_addr_outstanding_rewards_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/validators/{validatorAddr}/outstanding_rewards', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Coin]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_validators_validator_addr_rewards_get(self, validator_addr, **kwargs):  # noqa: E501
        """Commission and self-delegation rewards of a single validator  # noqa: E501

        Query the commission and self-delegation rewards of validator.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_rewards_get(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_validators_validator_addr_rewards_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_validators_validator_addr_rewards_get_with_http_info(validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_validators_validator_addr_rewards_get_with_http_info(self, validator_addr, **kwargs):  # noqa: E501
        """Commission and self-delegation rewards of a single validator  # noqa: E501

        Query the commission and self-delegation rewards of validator.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_rewards_get_with_http_info(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :return: list[Coin]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['validator_addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_validators_validator_addr_rewards_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_validators_validator_addr_rewards_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/validators/{validatorAddr}/rewards', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Coin]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def distribution_validators_validator_addr_rewards_post(self, validator_addr, **kwargs):  # noqa: E501
        """Withdraw the validator's rewards  # noqa: E501

        Withdraw the validator's self-delegation and commissions rewards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_rewards_post(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :param WithdrawRequestBody3 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.distribution_validators_validator_addr_rewards_post_with_http_info(validator_addr, **kwargs)  # noqa: E501
        else:
            (data) = self.distribution_validators_validator_addr_rewards_post_with_http_info(validator_addr, **kwargs)  # noqa: E501
            return data

    def distribution_validators_validator_addr_rewards_post_with_http_info(self, validator_addr, **kwargs):  # noqa: E501
        """Withdraw the validator's rewards  # noqa: E501

        Withdraw the validator's self-delegation and commissions rewards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.distribution_validators_validator_addr_rewards_post_with_http_info(validator_addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str validator_addr: Bech32 OperatorAddress of validator (required)
        :param WithdrawRequestBody3 withdraw_request_body:
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['validator_addr', 'withdraw_request_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method distribution_validators_validator_addr_rewards_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'validator_addr' is set
        if ('validator_addr' not in params or
                params['validator_addr'] is None):
            raise ValueError("Missing the required parameter `validator_addr` when calling `distribution_validators_validator_addr_rewards_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'validator_addr' in params:
            path_params['validatorAddr'] = params['validator_addr']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'withdraw_request_body' in params:
            body_params = params['withdraw_request_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/distribution/validators/{validatorAddr}/rewards', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
