# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class GovernanceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def gov_parameters_deposit_get(self, **kwargs):  # noqa: E501
        """Query governance deposit parameters  # noqa: E501

        Query governance deposit parameters. The max_deposit_period units are in nanoseconds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_deposit_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: InlineResponse2008
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_parameters_deposit_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.gov_parameters_deposit_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def gov_parameters_deposit_get_with_http_info(self, **kwargs):  # noqa: E501
        """Query governance deposit parameters  # noqa: E501

        Query governance deposit parameters. The max_deposit_period units are in nanoseconds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_deposit_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: InlineResponse2008
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_parameters_deposit_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/parameters/deposit', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2008',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_parameters_tallying_get(self, **kwargs):  # noqa: E501
        """Query governance tally parameters  # noqa: E501

        Query governance tally parameters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_tallying_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_parameters_tallying_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.gov_parameters_tallying_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def gov_parameters_tallying_get_with_http_info(self, **kwargs):  # noqa: E501
        """Query governance tally parameters  # noqa: E501

        Query governance tally parameters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_tallying_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_parameters_tallying_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/parameters/tallying', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_parameters_voting_get(self, **kwargs):  # noqa: E501
        """Query governance voting parameters  # noqa: E501

        Query governance voting parameters. The voting_period units are in nanoseconds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_voting_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_parameters_voting_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.gov_parameters_voting_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def gov_parameters_voting_get_with_http_info(self, **kwargs):  # noqa: E501
        """Query governance voting parameters  # noqa: E501

        Query governance voting parameters. The voting_period units are in nanoseconds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_parameters_voting_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_parameters_voting_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/parameters/voting', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_get(self, **kwargs):  # noqa: E501
        """Query proposals  # noqa: E501

        Query proposals information with parameters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str voter: voter address
        :param str depositor: depositor address
        :param str status: proposal status, valid values can be `\"deposit_period\"`, `\"voting_period\"`, `\"passed\"`, `\"rejected\"`
        :return: list[TextProposal]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def gov_proposals_get_with_http_info(self, **kwargs):  # noqa: E501
        """Query proposals  # noqa: E501

        Query proposals information with parameters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str voter: voter address
        :param str depositor: depositor address
        :param str status: proposal status, valid values can be `\"deposit_period\"`, `\"voting_period\"`, `\"passed\"`, `\"rejected\"`
        :return: list[TextProposal]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['voter', 'depositor', 'status']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'voter' in params:
            query_params.append(('voter', params['voter']))  # noqa: E501
        if 'depositor' in params:
            query_params.append(('depositor', params['depositor']))  # noqa: E501
        if 'status' in params:
            query_params.append(('status', params['status']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TextProposal]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_param_change_post(self, post_proposal_body, **kwargs):  # noqa: E501
        """Generate a parameter change proposal transaction  # noqa: E501

        Generate a parameter change proposal transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_param_change_post(post_proposal_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostProposalBody1 post_proposal_body: The parameter change proposal body that contains all parameter changes (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_param_change_post_with_http_info(post_proposal_body, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_param_change_post_with_http_info(post_proposal_body, **kwargs)  # noqa: E501
            return data

    def gov_proposals_param_change_post_with_http_info(self, post_proposal_body, **kwargs):  # noqa: E501
        """Generate a parameter change proposal transaction  # noqa: E501

        Generate a parameter change proposal transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_param_change_post_with_http_info(post_proposal_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostProposalBody1 post_proposal_body: The parameter change proposal body that contains all parameter changes (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['post_proposal_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_param_change_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'post_proposal_body' is set
        if ('post_proposal_body' not in params or
                params['post_proposal_body'] is None):
            raise ValueError("Missing the required parameter `post_proposal_body` when calling `gov_proposals_param_change_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'post_proposal_body' in params:
            body_params = params['post_proposal_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/param_change', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_post(self, post_proposal_body, **kwargs):  # noqa: E501
        """Submit a proposal  # noqa: E501

        Send transaction to submit a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_post(post_proposal_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostProposalBody post_proposal_body: valid value of `\"proposal_type\"` can be `\"text\"`, `\"parameter_change\"`, `\"software_upgrade\"` (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_post_with_http_info(post_proposal_body, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_post_with_http_info(post_proposal_body, **kwargs)  # noqa: E501
            return data

    def gov_proposals_post_with_http_info(self, post_proposal_body, **kwargs):  # noqa: E501
        """Submit a proposal  # noqa: E501

        Send transaction to submit a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_post_with_http_info(post_proposal_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostProposalBody post_proposal_body: valid value of `\"proposal_type\"` can be `\"text\"`, `\"parameter_change\"`, `\"software_upgrade\"` (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['post_proposal_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'post_proposal_body' is set
        if ('post_proposal_body' not in params or
                params['post_proposal_body'] is None):
            raise ValueError("Missing the required parameter `post_proposal_body` when calling `gov_proposals_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'post_proposal_body' in params:
            body_params = params['post_proposal_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_deposits_depositor_get(self, proposal_id, depositor, **kwargs):  # noqa: E501
        """Query deposit  # noqa: E501

        Query deposit by proposalId and depositor address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_depositor_get(proposal_id, depositor, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param str depositor: Bech32 depositor address (required)
        :return: Deposit
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_deposits_depositor_get_with_http_info(proposal_id, depositor, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_deposits_depositor_get_with_http_info(proposal_id, depositor, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_deposits_depositor_get_with_http_info(self, proposal_id, depositor, **kwargs):  # noqa: E501
        """Query deposit  # noqa: E501

        Query deposit by proposalId and depositor address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_depositor_get_with_http_info(proposal_id, depositor, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param str depositor: Bech32 depositor address (required)
        :return: Deposit
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id', 'depositor']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_deposits_depositor_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_deposits_depositor_get`")  # noqa: E501
        # verify the required parameter 'depositor' is set
        if ('depositor' not in params or
                params['depositor'] is None):
            raise ValueError("Missing the required parameter `depositor` when calling `gov_proposals_proposal_id_deposits_depositor_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501
        if 'depositor' in params:
            path_params['depositor'] = params['depositor']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/deposits/{depositor}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Deposit',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_deposits_get(self, proposal_id, **kwargs):  # noqa: E501
        """Query deposits  # noqa: E501

        Query deposits by proposalId  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_get(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: list[Deposit]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_deposits_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_deposits_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_deposits_get_with_http_info(self, proposal_id, **kwargs):  # noqa: E501
        """Query deposits  # noqa: E501

        Query deposits by proposalId  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_get_with_http_info(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: list[Deposit]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_deposits_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_deposits_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/deposits', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Deposit]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_deposits_post(self, proposal_id, post_deposit_body, **kwargs):  # noqa: E501
        """Deposit tokens to a proposal  # noqa: E501

        Send transaction to deposit tokens to a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_post(proposal_id, post_deposit_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param PostDepositBody post_deposit_body:  (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_deposits_post_with_http_info(proposal_id, post_deposit_body, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_deposits_post_with_http_info(proposal_id, post_deposit_body, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_deposits_post_with_http_info(self, proposal_id, post_deposit_body, **kwargs):  # noqa: E501
        """Deposit tokens to a proposal  # noqa: E501

        Send transaction to deposit tokens to a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_deposits_post_with_http_info(proposal_id, post_deposit_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param PostDepositBody post_deposit_body:  (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id', 'post_deposit_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_deposits_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_deposits_post`")  # noqa: E501
        # verify the required parameter 'post_deposit_body' is set
        if ('post_deposit_body' not in params or
                params['post_deposit_body'] is None):
            raise ValueError("Missing the required parameter `post_deposit_body` when calling `gov_proposals_proposal_id_deposits_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'post_deposit_body' in params:
            body_params = params['post_deposit_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/deposits', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_get(self, proposal_id, **kwargs):  # noqa: E501
        """Query a proposal  # noqa: E501

        Query a proposal by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_get(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: TextProposal
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_get_with_http_info(self, proposal_id, **kwargs):  # noqa: E501
        """Query a proposal  # noqa: E501

        Query a proposal by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_get_with_http_info(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: TextProposal
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TextProposal',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_proposer_get(self, proposal_id, **kwargs):  # noqa: E501
        """Query proposer  # noqa: E501

        Query for the proposer for a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_proposer_get(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: Proposer
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_proposer_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_proposer_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_proposer_get_with_http_info(self, proposal_id, **kwargs):  # noqa: E501
        """Query proposer  # noqa: E501

        Query for the proposer for a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_proposer_get_with_http_info(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: (required)
        :return: Proposer
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_proposer_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_proposer_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/proposer', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Proposer',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_tally_get(self, proposal_id, **kwargs):  # noqa: E501
        """Get a proposal's tally result at the current time  # noqa: E501

        Gets a proposal's tally result at the current time. If the proposal is pending deposits (i.e status 'DepositPeriod') it returns an empty tally result.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_tally_get(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :return: TallyResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_tally_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_tally_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_tally_get_with_http_info(self, proposal_id, **kwargs):  # noqa: E501
        """Get a proposal's tally result at the current time  # noqa: E501

        Gets a proposal's tally result at the current time. If the proposal is pending deposits (i.e status 'DepositPeriod') it returns an empty tally result.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_tally_get_with_http_info(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :return: TallyResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_tally_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_tally_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/tally', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TallyResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_votes_get(self, proposal_id, **kwargs):  # noqa: E501
        """Query voters  # noqa: E501

        Query voters information by proposalId  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_get(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :return: list[Vote]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_votes_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_votes_get_with_http_info(proposal_id, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_votes_get_with_http_info(self, proposal_id, **kwargs):  # noqa: E501
        """Query voters  # noqa: E501

        Query voters information by proposalId  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_get_with_http_info(proposal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :return: list[Vote]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_votes_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_votes_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/votes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Vote]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_votes_post(self, proposal_id, post_vote_body, **kwargs):  # noqa: E501
        """Vote a proposal  # noqa: E501

        Send transaction to vote a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_post(proposal_id, post_vote_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param PostVoteBody post_vote_body: valid value of `\"option\"` field can be `\"yes\"`, `\"no\"`, `\"no_with_veto\"` and `\"abstain\"` (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_votes_post_with_http_info(proposal_id, post_vote_body, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_votes_post_with_http_info(proposal_id, post_vote_body, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_votes_post_with_http_info(self, proposal_id, post_vote_body, **kwargs):  # noqa: E501
        """Vote a proposal  # noqa: E501

        Send transaction to vote a proposal  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_post_with_http_info(proposal_id, post_vote_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param PostVoteBody post_vote_body: valid value of `\"option\"` field can be `\"yes\"`, `\"no\"`, `\"no_with_veto\"` and `\"abstain\"` (required)
        :return: StdTx
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id', 'post_vote_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_votes_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_votes_post`")  # noqa: E501
        # verify the required parameter 'post_vote_body' is set
        if ('post_vote_body' not in params or
                params['post_vote_body'] is None):
            raise ValueError("Missing the required parameter `post_vote_body` when calling `gov_proposals_proposal_id_votes_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'post_vote_body' in params:
            body_params = params['post_vote_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/votes', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StdTx',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gov_proposals_proposal_id_votes_voter_get(self, proposal_id, voter, **kwargs):  # noqa: E501
        """Query vote  # noqa: E501

        Query vote information by proposal Id and voter address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_voter_get(proposal_id, voter, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param str voter: Bech32 voter address (required)
        :return: Vote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gov_proposals_proposal_id_votes_voter_get_with_http_info(proposal_id, voter, **kwargs)  # noqa: E501
        else:
            (data) = self.gov_proposals_proposal_id_votes_voter_get_with_http_info(proposal_id, voter, **kwargs)  # noqa: E501
            return data

    def gov_proposals_proposal_id_votes_voter_get_with_http_info(self, proposal_id, voter, **kwargs):  # noqa: E501
        """Query vote  # noqa: E501

        Query vote information by proposal Id and voter address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gov_proposals_proposal_id_votes_voter_get_with_http_info(proposal_id, voter, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str proposal_id: proposal id (required)
        :param str voter: Bech32 voter address (required)
        :return: Vote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['proposal_id', 'voter']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gov_proposals_proposal_id_votes_voter_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'proposal_id' is set
        if ('proposal_id' not in params or
                params['proposal_id'] is None):
            raise ValueError("Missing the required parameter `proposal_id` when calling `gov_proposals_proposal_id_votes_voter_get`")  # noqa: E501
        # verify the required parameter 'voter' is set
        if ('voter' not in params or
                params['voter'] is None):
            raise ValueError("Missing the required parameter `voter` when calling `gov_proposals_proposal_id_votes_voter_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'proposal_id' in params:
            path_params['proposalId'] = params['proposal_id']  # noqa: E501
        if 'voter' in params:
            path_params['voter'] = params['voter']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gov/proposals/{proposalId}/votes/{voter}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Vote',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
