# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.distribution_api import DistributionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDistributionApi(unittest.TestCase):
    """DistributionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.distribution_api.DistributionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_distribution_community_pool_get(self):
        """Test case for distribution_community_pool_get

        Community pool parameters  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_rewards_get(self):
        """Test case for distribution_delegators_delegator_addr_rewards_get

        Get the total rewards balance from all delegations  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_rewards_post(self):
        """Test case for distribution_delegators_delegator_addr_rewards_post

        Withdraw all the delegator's delegation rewards  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_rewards_validator_addr_get(self):
        """Test case for distribution_delegators_delegator_addr_rewards_validator_addr_get

        Query a delegation reward  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_rewards_validator_addr_post(self):
        """Test case for distribution_delegators_delegator_addr_rewards_validator_addr_post

        Withdraw a delegation reward  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_withdraw_address_get(self):
        """Test case for distribution_delegators_delegator_addr_withdraw_address_get

        Get the rewards withdrawal address  # noqa: E501
        """
        pass

    def test_distribution_delegators_delegator_addr_withdraw_address_post(self):
        """Test case for distribution_delegators_delegator_addr_withdraw_address_post

        Replace the rewards withdrawal address  # noqa: E501
        """
        pass

    def test_distribution_parameters_get(self):
        """Test case for distribution_parameters_get

        Fee distribution parameters  # noqa: E501
        """
        pass

    def test_distribution_validators_validator_addr_get(self):
        """Test case for distribution_validators_validator_addr_get

        Validator distribution information  # noqa: E501
        """
        pass

    def test_distribution_validators_validator_addr_outstanding_rewards_get(self):
        """Test case for distribution_validators_validator_addr_outstanding_rewards_get

        Fee distribution outstanding rewards of a single validator  # noqa: E501
        """
        pass

    def test_distribution_validators_validator_addr_rewards_get(self):
        """Test case for distribution_validators_validator_addr_rewards_get

        Commission and self-delegation rewards of a single validator  # noqa: E501
        """
        pass

    def test_distribution_validators_validator_addr_rewards_post(self):
        """Test case for distribution_validators_validator_addr_rewards_post

        Withdraw the validator's rewards  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
