# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.supply_api import SupplyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupplyApi(unittest.TestCase):
    """SupplyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.supply_api.SupplyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_supply_total_denomination_get(self):
        """Test case for supply_total_denomination_get

        Total supply of a single coin denomination  # noqa: E501
        """
        pass

    def test_supply_total_get(self):
        """Test case for supply_total_get

        Total supply of coins in the chain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
