# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.slashing_api import SlashingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSlashingApi(unittest.TestCase):
    """SlashingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.slashing_api.SlashingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_slashing_parameters_get(self):
        """Test case for slashing_parameters_get

        Get the current slashing parameters  # noqa: E501
        """
        pass

    def test_slashing_signing_infos_get(self):
        """Test case for slashing_signing_infos_get

        Get sign info of given all validators  # noqa: E501
        """
        pass

    def test_slashing_validators_validator_addr_unjail_post(self):
        """Test case for slashing_validators_validator_addr_unjail_post

        Unjail a jailed validator  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
