# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bank_api import BankApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBankApi(unittest.TestCase):
    """BankApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bank_api.BankApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bank_accounts_address_transfers_post(self):
        """Test case for bank_accounts_address_transfers_post

        Send coins from one account to another  # noqa: E501
        """
        pass

    def test_bank_balances_address_get(self):
        """Test case for bank_balances_address_get

        Get the account balances  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
