# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.governance_api import GovernanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGovernanceApi(unittest.TestCase):
    """GovernanceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.governance_api.GovernanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gov_parameters_deposit_get(self):
        """Test case for gov_parameters_deposit_get

        Query governance deposit parameters  # noqa: E501
        """
        pass

    def test_gov_parameters_tallying_get(self):
        """Test case for gov_parameters_tallying_get

        Query governance tally parameters  # noqa: E501
        """
        pass

    def test_gov_parameters_voting_get(self):
        """Test case for gov_parameters_voting_get

        Query governance voting parameters  # noqa: E501
        """
        pass

    def test_gov_proposals_get(self):
        """Test case for gov_proposals_get

        Query proposals  # noqa: E501
        """
        pass

    def test_gov_proposals_param_change_post(self):
        """Test case for gov_proposals_param_change_post

        Generate a parameter change proposal transaction  # noqa: E501
        """
        pass

    def test_gov_proposals_post(self):
        """Test case for gov_proposals_post

        Submit a proposal  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_deposits_depositor_get(self):
        """Test case for gov_proposals_proposal_id_deposits_depositor_get

        Query deposit  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_deposits_get(self):
        """Test case for gov_proposals_proposal_id_deposits_get

        Query deposits  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_deposits_post(self):
        """Test case for gov_proposals_proposal_id_deposits_post

        Deposit tokens to a proposal  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_get(self):
        """Test case for gov_proposals_proposal_id_get

        Query a proposal  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_proposer_get(self):
        """Test case for gov_proposals_proposal_id_proposer_get

        Query proposer  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_tally_get(self):
        """Test case for gov_proposals_proposal_id_tally_get

        Get a proposal's tally result at the current time  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_votes_get(self):
        """Test case for gov_proposals_proposal_id_votes_get

        Query voters  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_votes_post(self):
        """Test case for gov_proposals_proposal_id_votes_post

        Vote a proposal  # noqa: E501
        """
        pass

    def test_gov_proposals_proposal_id_votes_voter_get(self):
        """Test case for gov_proposals_proposal_id_votes_voter_get

        Query vote  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
