# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mint_api import MintApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMintApi(unittest.TestCase):
    """MintApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.mint_api.MintApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_minting_annual_provisions_get(self):
        """Test case for minting_annual_provisions_get

        Current minting annual provisions value  # noqa: E501
        """
        pass

    def test_minting_inflation_get(self):
        """Test case for minting_inflation_get

        Current minting inflation value  # noqa: E501
        """
        pass

    def test_minting_parameters_get(self):
        """Test case for minting_parameters_get

        Minting module parameters  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
