# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tendermint_rpc_api import TendermintRPCApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTendermintRPCApi(unittest.TestCase):
    """TendermintRPCApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tendermint_rpc_api.TendermintRPCApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_blocks_height_get(self):
        """Test case for blocks_height_get

        Get a block at a certain height  # noqa: E501
        """
        pass

    def test_blocks_latest_get(self):
        """Test case for blocks_latest_get

        Get the latest block  # noqa: E501
        """
        pass

    def test_syncing_get(self):
        """Test case for syncing_get

        Syncing state of node  # noqa: E501
        """
        pass

    def test_validatorsets_height_get(self):
        """Test case for validatorsets_height_get

        Get a validator set a certain height  # noqa: E501
        """
        pass

    def test_validatorsets_latest_get(self):
        """Test case for validatorsets_latest_get

        Get the latest validator set  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
