# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transactions_api import TransactionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_txs_decode_post(self):
        """Test case for txs_decode_post

        Decode a transaction from the Amino wire format  # noqa: E501
        """
        pass

    def test_txs_encode_post(self):
        """Test case for txs_encode_post

        Encode a transaction to the Amino wire format  # noqa: E501
        """
        pass

    def test_txs_get(self):
        """Test case for txs_get

        Search transactions  # noqa: E501
        """
        pass

    def test_txs_hash_get(self):
        """Test case for txs_hash_get

        Get a Tx by hash  # noqa: E501
        """
        pass

    def test_txs_post(self):
        """Test case for txs_post

        Broadcast a signed tx  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
