# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StdTxSignatures(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'signature': 'str',
        'pub_key': 'StdTxPubKey',
        'account_number': 'str',
        'sequence': 'str'
    }

    attribute_map = {
        'signature': 'signature',
        'pub_key': 'pub_key',
        'account_number': 'account_number',
        'sequence': 'sequence'
    }

    def __init__(self, signature=None, pub_key=None, account_number=None, sequence=None):  # noqa: E501
        """StdTxSignatures - a model defined in Swagger"""  # noqa: E501

        self._signature = None
        self._pub_key = None
        self._account_number = None
        self._sequence = None
        self.discriminator = None

        if signature is not None:
            self.signature = signature
        if pub_key is not None:
            self.pub_key = pub_key
        if account_number is not None:
            self.account_number = account_number
        if sequence is not None:
            self.sequence = sequence

    @property
    def signature(self):
        """Gets the signature of this StdTxSignatures.  # noqa: E501


        :return: The signature of this StdTxSignatures.  # noqa: E501
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this StdTxSignatures.


        :param signature: The signature of this StdTxSignatures.  # noqa: E501
        :type: str
        """

        self._signature = signature

    @property
    def pub_key(self):
        """Gets the pub_key of this StdTxSignatures.  # noqa: E501


        :return: The pub_key of this StdTxSignatures.  # noqa: E501
        :rtype: StdTxPubKey
        """
        return self._pub_key

    @pub_key.setter
    def pub_key(self, pub_key):
        """Sets the pub_key of this StdTxSignatures.


        :param pub_key: The pub_key of this StdTxSignatures.  # noqa: E501
        :type: StdTxPubKey
        """

        self._pub_key = pub_key

    @property
    def account_number(self):
        """Gets the account_number of this StdTxSignatures.  # noqa: E501


        :return: The account_number of this StdTxSignatures.  # noqa: E501
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number):
        """Sets the account_number of this StdTxSignatures.


        :param account_number: The account_number of this StdTxSignatures.  # noqa: E501
        :type: str
        """

        self._account_number = account_number

    @property
    def sequence(self):
        """Gets the sequence of this StdTxSignatures.  # noqa: E501


        :return: The sequence of this StdTxSignatures.  # noqa: E501
        :rtype: str
        """
        return self._sequence

    @sequence.setter
    def sequence(self, sequence):
        """Sets the sequence of this StdTxSignatures.


        :param sequence: The sequence of this StdTxSignatures.  # noqa: E501
        :type: str
        """

        self._sequence = sequence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StdTxSignatures, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StdTxSignatures):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
