# coding: utf-8

"""
    API for Secret Network by ChainofSecrets.org

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ValidatorSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'validators': 'list[IBCValidator]',
        'proposer': 'IBCValidator'
    }

    attribute_map = {
        'validators': 'validators',
        'proposer': 'proposer'
    }

    def __init__(self, validators=None, proposer=None):  # noqa: E501
        """ValidatorSet - a model defined in Swagger"""  # noqa: E501

        self._validators = None
        self._proposer = None
        self.discriminator = None

        if validators is not None:
            self.validators = validators
        if proposer is not None:
            self.proposer = proposer

    @property
    def validators(self):
        """Gets the validators of this ValidatorSet.  # noqa: E501


        :return: The validators of this ValidatorSet.  # noqa: E501
        :rtype: list[IBCValidator]
        """
        return self._validators

    @validators.setter
    def validators(self, validators):
        """Sets the validators of this ValidatorSet.


        :param validators: The validators of this ValidatorSet.  # noqa: E501
        :type: list[IBCValidator]
        """

        self._validators = validators

    @property
    def proposer(self):
        """Gets the proposer of this ValidatorSet.  # noqa: E501


        :return: The proposer of this ValidatorSet.  # noqa: E501
        :rtype: IBCValidator
        """
        return self._proposer

    @proposer.setter
    def proposer(self, proposer):
        """Sets the proposer of this ValidatorSet.


        :param proposer: The proposer of this ValidatorSet.  # noqa: E501
        :type: IBCValidator
        """

        self._proposer = proposer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidatorSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidatorSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
